services:
  # FastAPI Application
  app:
    environment:
      DATABASE_SERVICE: ${DATABASE_SERVICE:-sqlite+aiosqlite}
      DATABASE_URL: ${DATABASE_URL:-sqlite:///./app.db}

    volumes:
      - ../app.db:/app/app.db

volumes:
  sqlite_data:
    driver: local
